# -*- coding: utf-8 -*-
# Treści podstron usług OzODent

SERVICES = [
  dict(slug="stomatologia-zachowawcza", name="Stomatologia zachowawcza", icon="tooth-fill",
    short="Leczenie próchnicy, estetyczne wypełnienia i odbudowa zębów – także kilka wypełnień na jednej wizycie.",
    hero="Leczenie próchnicy i odbudowa zębów z użyciem nowoczesnych nanokompozytów.",
    intro=["Stomatologia zachowawcza to podstawa zdrowego uśmiechu. Zajmujemy się leczeniem próchnicy, odbudową uszkodzonych zębów oraz estetycznymi korektami kształtu i koloru.",
           "Pracujemy na najnowszych nanokompozytach dających efekt kameleona – wypełnienie dopasowuje się do koloru naturalnego zęba i staje się praktycznie niewidoczne. Tam, gdzie to możliwe, wykonujemy kilka wypełnień na jednej wizycie – szybko, skutecznie i komfortowo, oszczędzając Twój czas."],
    scope=["Wypełnienia na jednej i wielu powierzchniach", "Rozległe odbudowy korony zęba kompozytem", "Leczenie ubytków klinowych (niepróchnicowych)",
           "Licówki kompozytowe – bezpośrednie i iniekcyjne (flow injection)", "Bonding i infiltracja ICON", "Szynowanie rozchwianych zębów"],
    benefits=[("tooth","Niewidoczne wypełnienia","Nanokompozyty z efektem kameleona idealnie dopasowane kolorem."),
              ("clock","Kilka wypełnień na wizycie","Mniej wizyt, mniej stresu i oszczędność czasu."),
              ("shield","Komfort leczenia","Znieczulenie w cenie zabiegu i delikatne podejście.")],
    prices=["zachowawcza"],
    faq=[("Czy leczenie próchnicy boli?","Zabiegi wykonujemy w znieczuleniu miejscowym, które jest wliczone w cenę zabiegu. Dzięki temu leczenie przebiega komfortowo."),
         ("Ile wypełnień można wykonać na jednej wizycie?","To zależy od stanu uzębienia i komfortu Pacjenta. Po przeglądzie lekarz zaproponuje plan, który często pozwala wykonać kilka wypełnień podczas jednej, dłuższej wizyty."),
         ("Czym jest licówka kompozytowa iniekcyjna?","To metoda flow injection, w której kompozyt wprowadzany jest do precyzyjnie przygotowanego szablonu. Pozwala uzyskać powtarzalny, estetyczny kształt zębów bez szlifowania.")]),

  dict(slug="stomatologia-dziecieca", name="Stomatologia dziecięca", icon="tooth-kid",
    short="Przyjazne podejście, profilaktyka i leczenie zębów u dzieci w każdym wieku.",
    hero="Delikatna opieka i leczenie dzieci – w przyjaznej atmosferze, bez pośpiechu.",
    intro=["Pierwsze wizyty u dentysty kształtują stosunek dziecka do leczenia na całe życie. Dlatego pracujemy z cierpliwością, w przyjaznej atmosferze i z indywidualnym podejściem do każdego małego Pacjenta.",
           "Oferujemy przeglądy, profilaktykę (lakierowanie, fluoryzację), leczenie zębów mlecznych i stałych, a także ocenę rozwoju uzębienia i zgryzu w okresie wymiany zębów. Zdrowy uśmiech Twojego dziecka to nasz priorytet!"],
    scope=["Przeglądy stomatologiczne i wizyty adaptacyjne", "Ocena rozwoju uzębienia i zgryzu (z OPG)", "Fluoryzacja i profilaktyka próchnicy",
           "Leczenie zębów mlecznych i stałych", "Usuwanie zębów mlecznych, także w reinkluzji", "Podcinanie wędzidełek we współpracy z neurologopedą"],
    benefits=[("heart","Przyjazna atmosfera","Spokojne tempo i cierpliwość – dziecko czuje się bezpiecznie."),
              ("baby","Profilaktyka od początku","Wskazówki dla rodziców i indywidualne zalecenia."),
              ("people","Możliwość sedacji","Sedacja farmakologiczna przy trudniejszych zabiegach.")],
    prices=["higienizacja"],
    faq=[("Kiedy pierwsza wizyta dziecka u dentysty?","Zalecamy pierwszą wizytę po wyrznięciu się pierwszych zębów, najpóźniej około 1. roku życia. To przede wszystkim wizyta adaptacyjna i okazja do rozmowy z rodzicami."),
         ("Czy warto leczyć zęby mleczne?","Tak. Zęby mleczne utrzymują miejsce dla zębów stałych, a nieleczona próchnica może prowadzić do bólu, stanów zapalnych i problemów ze zgryzem."),
         ("Ile kosztuje przegląd dziecka?","W ramach promocji na otwarcie przegląd stomatologiczny dla dzieci kosztuje 80 zł, a przegląd z ewaluacją ortodontyczną i zdjęciem OPG – 150 zł.")]),

  dict(slug="endodoncja", name="Endodoncja", icon="tooth-root",
    short="Jednoetapowe leczenie kanałowe wykonywane z najwyższą starannością.",
    hero="Jednoetapowe leczenie kanałowe – ratujemy zęby, które wydają się stracone.",
    intro=["Leczenie kanałowe (endodontyczne) pozwala uratować ząb, w którym doszło do zapalenia lub martwicy miazgi. Usuwamy zakażoną tkankę, dokładnie oczyszczamy i dezynfekujemy kanały, a następnie szczelnie je wypełniamy.",
           "W wielu przypadkach leczenie wykonujemy jednoetapowo – na jednej wizycie. Precyzyjną diagnostykę zapewniają zdjęcia RVG oraz tomografia CBCT dostępne na miejscu."],
    scope=["Diagnostyka RVG i CBCT na miejscu", "Jednoetapowe leczenie kanałowe", "Odbudowa ściany zęba przed leczeniem endodontycznym",
           "Odbudowa zęba po leczeniu kanałowym", "Leczenie stanów zapalnych tkanek okołowierzchołkowych", "Resekcja wierzchołka korzenia (gdy wskazana)"],
    benefits=[("micro","Precyzyjna diagnostyka","Tomografia CBCT pokazuje anatomię kanałów w 3D."),
              ("clock","Często na jednej wizycie","Mniej wizyt i szybszy powrót do komfortu."),
              ("shield","Zdjęcia w trakcie gratis","Zdjęcia punktowe w trakcie leczenia bez dodatkowych opłat.")],
    prices=["rtg"],
    faq=[("Czy leczenie kanałowe boli?","Leczenie odbywa się w znieczuleniu miejscowym. Po zabiegu może wystąpić przejściowa tkliwość, która zwykle mija po kilku dniach."),
         ("Ile kosztuje leczenie kanałowe?","Koszt zależy od liczby kanałów i stopnia trudności. Dokładną wycenę przedstawimy po konsultacji i wykonaniu zdjęcia RTG."),
         ("Co, jeśli ząb nie nadaje się do leczenia kanałowego?","Wtedy omówimy alternatywy – np. resekcję wierzchołka korzenia lub usunięcie zęba i odbudowę protetyczną bądź implant.")]),

  dict(slug="chirurgia", name="Chirurgia stomatologiczna", icon="implant",
    short="Pełen zakres zabiegów chirurgicznych: ekstrakcje, ósemki, torbiele, resekcje.",
    hero="Pełen zakres zabiegów chirurgicznych wykonywanych przez lekarza specjalistę.",
    intro=["Chirurgia stomatologiczna to specjalizacja lek. dent. Małgorzaty Pińkowskiej-Prasał. Wykonujemy zarówno proste ekstrakcje, jak i zabiegi zaawansowane – usuwanie zatrzymanych zębów ósmych, germektomię, wyłuszczanie torbieli czy resekcję wierzchołka korzenia.",
           "Każdy zabieg poprzedza dokładna diagnostyka (OPG lub CBCT na miejscu). Znieczulenie do każdego zabiegu chirurgicznego jest gratis, a jeśli szwy zakładane były w OzODent – wizyta kontrolna również jest bezpłatna."],
    scope=["Usuwanie zębów, w tym ze wskazań ortodontycznych", "Usuwanie zatrzymanych zębów ósmych", "Germektomia – usunięcie zawiązka zęba ósmego",
           "Plastyka połączenia ustno-zatokowego", "Wyłuszczanie torbieli i resekcja wierzchołka korzenia", "Wycięcie zmian na błonie śluzowej z badaniem histopatologicznym"],
    benefits=[("doctor","Lekarz specjalista","Specjalista chirurgii stomatologicznej z wieloletnim doświadczeniem."),
              ("shield","Znieczulenie gratis","Do każdego zabiegu chirurgicznego bez dopłat."),
              ("people","Możliwość sedacji","Sedacja farmakologiczna dla większego komfortu.")],
    prices=["chirurgia"],
    faq=[("Czy muszę usunąć ósemki?","Nie zawsze. Wskazaniem są m.in. stany zapalne, brak miejsca, zatrzymanie zęba lub zalecenie ortodonty. Decyzję podejmujemy po badaniu i zdjęciu OPG lub CBCT."),
         ("Jak przygotować się do zabiegu?","Zjedz lekki posiłek przed wizytą, poinformuj lekarza o przyjmowanych lekach i chorobach ogólnych. Szczegółowe zalecenia otrzymasz podczas konsultacji chirurgicznej."),
         ("Ile trwa gojenie po ekstrakcji?","Wstępne gojenie trwa zwykle 7–10 dni. Po zabiegu otrzymasz pisemne zalecenia, a wizyta kontrolna przy szwach zakładanych w OzODent jest gratis.")]),

  dict(slug="periodontologia", name="Periodontologia", icon="shield",
    short="Leczenie chorób dziąseł i przyzębia, kiretaż, leczenie zmian błony śluzowej.",
    hero="Zdrowe dziąsła to fundament zdrowych zębów.",
    intro=["Krwawienie dziąseł, nieprzyjemny zapach z ust czy rozchwianie zębów mogą być objawami choroby przyzębia. Im wcześniej rozpoczęte leczenie, tym większa szansa na zachowanie własnych zębów.",
           "Wykonujemy kiretaż poddziąsłowy (od pojedynczych zębów po całe uzębienie), drenaż ropni przyzębnych oraz leczenie zmian na błonie śluzowej jamy ustnej – także odleżyn spowodowanych protezą."],
    scope=["Konsultacja i kwalifikacja do zabiegu", "Kiretaż poddziąsłowy – 1–3 zęby, ćwiartka, łuk, całe uzębienie", "Drenaż ropnia przyzębnego z aplikacją leku",
           "Leczenie zmian na błonie śluzowej i odleżyn protetycznych", "Plastyka wyrostka zębodołowego", "Wycięcie zmian z badaniem histopatologicznym"],
    benefits=[("tooth","Ratujemy własne zęby","Leczenie zatrzymuje postęp choroby przyzębia."),
              ("shield","Znieczulenie gratis","Do zabiegów periodontologicznych bez dopłat."),
              ("heart","Indywidualne podejście","Plan leczenia dopasowany do stanu dziąseł.")],
    prices=["periodontologia"],
    faq=[("Czym jest kiretaż?","To zabieg oczyszczenia kieszonek dziąsłowych z kamienia poddziąsłowego i zmienionej zapalnie tkanki. Wykonywany jest w znieczuleniu."),
         ("Dziąsła krwawią przy myciu – czy to powód do wizyty?","Tak. Krwawienie to najczęstszy wczesny objaw zapalenia dziąseł. Warto zgłosić się na konsultację i higienizację."),
         ("Proteza obciera dziąsło – co robić?","Umów się na wizytę. Wykonujemy korektę protez wykonanych poza gabinetem oraz aplikujemy lek na odleżynę.")]),

  dict(slug="protetyka", name="Protetyka", icon="crown",
    short="Korony, mosty, protezy oraz odbudowy estetyczne i funkcjonalne.",
    hero="Odbudowa estetyczna i funkcjonalna – przywracamy pełny, pewny uśmiech.",
    intro=["Protetyka pozwala odbudować zęby zniszczone lub uzupełnić braki. Dobieramy rozwiązanie do potrzeb Pacjenta – od pojedynczej korony, przez mosty, po protezy ruchome.",
           "Plan leczenia protetycznego przygotowujemy po dokładnej diagnostyce i omawiamy go razem z kosztorysem, tak aby decyzja była w pełni świadoma."],
    scope=["Korony protetyczne", "Mosty protetyczne", "Protezy ruchome – częściowe i całkowite",
           "Odbudowy z bondingiem i estetyką", "Korekty i naprawy protez", "Uzupełnienia na implantach"],
    benefits=[("tooth","Estetyka i funkcja","Naturalny wygląd i komfort żucia."),
              ("micro","Diagnostyka 3D","Plan oparty na badaniu CBCT i OPG."),
              ("chat","Jasny kosztorys","Omówienie planu leczenia i kosztów przed startem.")],
    prices=[],
    faq=[("Ile kosztuje korona lub most?","Cena zależy od materiału i zakresu prac. Wycenę przygotujemy po konsultacji – w promocji na otwarcie konsultacja z OPG i kosztorysem kosztuje 200 zł."),
         ("Korona czy implant?","To zależy od stanu zęba i kości. Podczas konsultacji omówimy zalety obu rozwiązań w Twoim przypadku.")]),

  dict(slug="implanty", name="Implanty", icon="implant",
    short="Nowoczesne implanty – trwałe rozwiązanie w miejsce utraconych zębów.",
    hero="Nowoczesne implanty – trwałe rozwiązanie na lata.",
    intro=["Implant zastępuje korzeń utraconego zęba i stanowi stabilną podstawę dla korony, mostu lub protezy. To rozwiązanie, które przywraca komfort jedzenia, mówienia i pewność siebie.",
           "Kwalifikację do leczenia implantologicznego opieramy na tomografii CBCT wykonywanej na miejscu. Zabiegi przeprowadza specjalista chirurgii stomatologicznej."],
    scope=["Konsultacja i kwalifikacja z CBCT", "Planowanie leczenia implantologicznego", "Wprowadzenie implantu",
           "Uzupełnienia protetyczne na implantach", "Kontrola i opieka po leczeniu"],
    benefits=[("micro","Planowanie 3D","Tomografia CBCT na miejscu."),
              ("doctor","Specjalista chirurg","Zabiegi wykonuje lekarz specjalista."),
              ("shield","Trwałe rozwiązanie","Stabilność i naturalny wygląd na lata.")],
    prices=["rtg"],
    faq=[("Czy każdy może mieć implant?","Większość dorosłych Pacjentów tak. Kwalifikacja zależy m.in. od ilości kości i stanu zdrowia ogólnego – ocenimy to na konsultacji z CBCT."),
         ("Ile kosztuje implant?","Koszt zależy od zakresu leczenia i rodzaju uzupełnienia. Indywidualny kosztorys przedstawimy po konsultacji chirurgicznej.")]),

  dict(slug="podcinanie-wedzidelek", name="Podcinanie wędzidełek", icon="baby",
    short="U niemowląt, starszych dzieci i dorosłych – we współpracy z neurologopedą.",
    hero="Podcinanie wędzidełek u niemowląt, dzieci i dorosłych – we współpracy z neurologopedą.",
    intro=["Zbyt krótkie wędzidełko języka lub wargi może utrudniać karmienie piersią, rozwój mowy, prawidłowe połykanie i oddychanie. Zabieg podcięcia wykonujemy precyzyjnie i delikatnie – od noworodków po dorosłych.",
           "Wszystkie zabiegi wykonywane są w porozumieniu z neurologopedą i logopedą oraz w ramach prowadzonej terapii neurologopedycznej / logopedycznej. W razie potrzeby istnieje możliwość zastosowania sedacji farmakologicznej przed zabiegiem."],
    scope=["Konsultacja i kwalifikacja do zabiegu", "Frenotomia u noworodków i niemowląt", "Powtórne podcięcie – wycięcie zrostu u niemowląt",
           "Miofrenuloplastyka u starszych dzieci (od 5 r.ż.) i dorosłych", "Podcięcie wędzidełka wargi górnej"],
    benefits=[("brain","Współpraca z neurologopedą","Zabieg jako część kompleksowej terapii."),
              ("doctor","Specjalista chirurg","Precyzja i doświadczenie w zabiegach u najmłodszych."),
              ("syringe","Możliwość sedacji","Sedacja farmakologiczna, gdy jest potrzebna.")],
    prices=["wedzidelka"],
    faq=[("Jakie są objawy zbyt krótkiego wędzidełka u niemowlęcia?","Najczęściej trudności z przystawianiem do piersi, cmokanie, szybkie męczenie się przy karmieniu czy ból brodawek u mamy. Ostateczną ocenę przeprowadza się podczas konsultacji, najlepiej we współpracy z neurologopedą."),
         ("Czym jest miofrenuloplastyka?","To zabieg podcięcia wędzidełka języka u starszych dzieci i dorosłych, uwzględniający podcięcie mięśni bródkowo-językowych, wykonywany w ramach terapii logopedycznej."),
         ("Czy potrzebuję skierowania od logopedy?","Skierowanie nie jest wymagane, ale zabiegi wykonujemy w porozumieniu z neurologopedą lub logopedą prowadzącym terapię.")]),

  dict(slug="higienizacja-wybielanie", name="Higienizacja i wybielanie", icon="tooth",
    short="Skaling, piaskowanie, fluoryzacja i wybielanie nakładkowe.",
    hero="Nowoczesna higienizacja i wybielanie wykonywane przez wykwalifikowany personel.",
    intro=["Regularna higienizacja to najprostszy sposób, by zapobiegać próchnicy i chorobom dziąseł. Usuwamy kamień nad- i poddziąsłowy, osad i przebarwienia, a na koniec zabezpieczamy szkliwo lakierem z fluorem.",
           "Dla osób, które marzą o jaśniejszym uśmiechu, oferujemy wybielanie nakładkowe – bezpieczną metodę domową pod kontrolą lekarza."],
    scope=["Skaling – usuwanie kamienia", "Piaskowanie – usuwanie osadów i przebarwień", "Pełna higienizacja z lakierowaniem",
           "Fluoryzacja 1 lub 2 łuków", "Wybielanie nakładkowe (2 łuki zębowe)"],
    benefits=[("tooth","Zdrowe dziąsła","Profilaktyka próchnicy i paradontozy."),
              ("heart","Świeży uśmiech","Usunięcie przebarwień po kawie, herbacie i papierosach."),
              ("shield","Bezpieczne wybielanie","Nakładki wykonane indywidualnie, pod kontrolą lekarza.")],
    prices=["higienizacja"],
    faq=[("Jak często robić higienizację?","Zwykle co 6 miesięcy. Osobom z chorobami przyzębia lub aparatem ortodontycznym zalecamy częstsze wizyty."),
         ("Czy wybielanie niszczy szkliwo?","Wybielanie nakładkowe wykonywane zgodnie z zaleceniami lekarza jest bezpieczne. Przejściowa nadwrażliwość może się pojawić, ale zwykle szybko mija.")]),

  dict(slug="medycyna-estetyczna", name="Medycyna estetyczna", icon="face",
    short="Kwas hialuronowy, botoks i zabiegi odmładzające.",
    hero="Zabiegi odmładzające i upiększające – naturalny efekt w dobrych rękach.",
    intro=["Uzupełnieniem pięknego uśmiechu są zabiegi medycyny estetycznej. Wykonujemy zabiegi z użyciem kwasu hialuronowego oraz toksyny botulinowej, dbając o naturalny i harmonijny efekt.",
           "Każdy zabieg poprzedza konsultacja, podczas której omawiamy oczekiwania, przeciwwskazania i możliwe efekty."],
    scope=["Konsultacja estetyczna", "Kwas hialuronowy – modelowanie ust i wypełnianie zmarszczek", "Toksyna botulinowa (botoks) – zmarszczki mimiczne",
           "Zabiegi poprawiające owal twarzy"],
    benefits=[("face","Naturalny efekt","Subtelne, harmonijne rezultaty."),
              ("doctor","Lekarz z doświadczeniem","Zabiegi wykonuje lekarz dentysta."),
              ("chat","Konsultacja przed zabiegiem","Omówienie oczekiwań i przeciwwskazań.")],
    prices=[],
    faq=[("Ile utrzymuje się efekt?","Efekt kwasu hialuronowego utrzymuje się zwykle od kilku do kilkunastu miesięcy, a toksyny botulinowej około 3–6 miesięcy – zależnie od preparatu i organizmu."),
         ("Ile kosztują zabiegi?","Cena zależy od preparatu i zakresu zabiegu. Wycenę przedstawimy podczas konsultacji.")]),

  dict(slug="diagnostyka-rtg", name="Diagnostyka CBCT i OPG", icon="micro",
    short="Tomografia CBCT, zdjęcia pantomograficzne i RVG na miejscu.",
    hero="Precyzyjna diagnostyka 3D i panoramiczna – bez wychodzenia z gabinetu.",
    intro=["Nowoczesna diagnostyka radiologiczna to podstawa skutecznego leczenia. W OzODent wykonasz na miejscu zdjęcie punktowe RVG, zdjęcie pantomograficzne (OPG) oraz tomografię komputerową CBCT.",
           "Tomografia CBCT daje trójwymiarowy obraz zębów i kości – niezbędny przy planowaniu zabiegów chirurgicznych, implantologicznych i trudnego leczenia kanałowego. Zdjęcia punktowe wykorzystywane w trakcie leczenia są gratis."],
    scope=["Zdjęcie punktowe RVG", "Zdjęcie pantomograficzne (OPG)", "Tomografia wycinkowa",
           "Tomografia jednego łuku (szczęka lub żuchwa)", "Tomografia całkowita (szczęka + żuchwa)"],
    benefits=[("micro","Obraz 3D","Precyzyjna diagnostyka CBCT."),
              ("clock","Na miejscu","Bez szukania pracowni RTG i dodatkowych wizyt."),
              ("shield","Zdjęcia w trakcie gratis","Zdjęcia punktowe podczas leczenia bez opłat.")],
    prices=["rtg"],
    faq=[("Czy mogę wykonać samo zdjęcie bez leczenia?","Tak, wykonujemy zdjęcia RTG i tomografię także jako osobne badanie."),
         ("Czy badanie jest bezpieczne?","Nowoczesne aparaty stosują niskie dawki promieniowania. Badanie zlecamy tylko wtedy, gdy jest potrzebne do diagnostyki.")]),
]
